name: CI
on: [ push, pull_request, workflow_dispatch ]
jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-20.04
            nginx-version: 1.21.1
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        volumes:
          - ${{ github.workspace }}:/workspace
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
          APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE: 1
        run: |
          # for Test::Nginx
          curl -sSL "https://openresty.org/package/pubkey.gpg" | sudo -E apt-key add -
          echo "deb https://openresty.org/package/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/openresty.list
          sudo apt-get update
          sudo -E apt-get install -y libtest-nginx-perl
      - name: Install nginx
        env:
          NGINX_VERSION: ${{ matrix.nginx-version }}
        run: ci/install-nginx.sh --add-module=${{ github.workspace }}/
      - name: Build Redis rate limiter module
        run: ci/build-rate-limiter.sh
      - name: Load Redis rate limiter module
        run: docker exec ${{ job.services.redis.id }} sh -c 'redis-cli MODULE LOAD /workspace/rate-limiter/ratelimit.so'
      - name: Prepare environment
        run: echo "$HOME/nginx/sbin" >> $GITHUB_PATH
      - name: Run integration tests
        run: prove -r t
